// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJX0Y8smR14dVyMihWOzgJzai4afHFr6s',
    appId: '1:70773020588:web:82d1d0840dd83c96368c09',
    messagingSenderId: '70773020588',
    projectId: 'spire-e7294',
    authDomain: 'spire-e7294.firebaseapp.com',
    storageBucket: 'spire-e7294.appspot.com',
    measurementId: 'G-3F1RSJ9198',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpKtMLRs7jUteJFDTrr90dl37LmdnuCw4',
    appId: '1:70773020588:android:fc1fb592d245b0ec368c09',
    messagingSenderId: '70773020588',
    projectId: 'spire-e7294',
    storageBucket: 'spire-e7294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBur0z-RRFgcK4gXmiBg6KYkwfLWXY0wxc',
    appId: '1:70773020588:ios:770877bf741649c2368c09',
    messagingSenderId: '70773020588',
    projectId: 'spire-e7294',
    storageBucket: 'spire-e7294.appspot.com',
    iosBundleId: 'com.example.spire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBur0z-RRFgcK4gXmiBg6KYkwfLWXY0wxc',
    appId: '1:70773020588:ios:34656dac072c848a368c09',
    messagingSenderId: '70773020588',
    projectId: 'spire-e7294',
    storageBucket: 'spire-e7294.appspot.com',
    iosBundleId: 'com.example.spire.RunnerTests',
  );
}
